### PR TITLE
added: multiple unique HTML tags

### PR DESCRIPTION
**Pull request by casafurix**
Multiple unknown and cool HTML tags added.

### CODE REVIEW

**Review by AnuragAnalog — COMMENTED** [review]
@casafurix Just check for the merge conflicts

**Comment by casafurix** [comment]
actually i am not getting what to solve, i think its because another commit got added, how do i fix this?

**Comment by casafurix** [comment]
please check and verify, i have made the changes, thanks in advance

**Comment by AnuragAnalog** [comment]
@casafurix accepted your pull request 😊

**Comment by casafurix** [comment]
thanks a lot!

**Pull request merged**
