### PR TITLE
added html tag for progress bar

### PR DESCRIPTION
**Pull request by smil-thakur**
@AnuragAnalog added a tag in cheatsheet.html for progress bar using plain CSS

### CODE REVIEW

**Review by AnuragAnalog — APPROVED** [review]
It's looking good

**Comment by AnuragAnalog** [comment]
@smil-thakur accepted your pull request

**Comment by smil-thakur** [comment]
thanks bro really glad to hear appreciation from you. respect bro

**Comment by smil-thakur** [comment]
And also can you add hacktoberfest-accepted tag
please thanks in adv @AnuragAnalog

**Comment by smil-thakur** [comment]
@AnuragAnalog bro hacktoberfest-accepted tag would be really helpful

**Comment by AnuragAnalog** [comment]
Sure @smil-thakur

**Pull request merged**
